/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/banner/banner.vue')['default']
    Category: typeof import('./src/components/category/category.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Hero: typeof import('./src/components/hero/hero.vue')['default']
    HotList: typeof import('./src/components/hotList/hotList.vue')['default']
    HotRadioList: typeof import('./src/components/hotRadioList/hotRadioList.vue')['default']
    HotSingerList: typeof import('./src/components/hotSingerList/hotSingerList.vue')['default']
    Left: typeof import('./src/components/main/left/Left.vue')['default']
    List: typeof import('./src/components/list/list.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    MvDetail: typeof import('./src/components/mvDetail/mvDetail.vue')['default']
    MvList: typeof import('./src/components/mvList/mvList.vue')['default']
    NewDisc: typeof import('./src/components/newDisc/newDisc.vue')['default']
    PlayBar: typeof import('./src/components/playBar/playBar.vue')['default']
    PlayListDetail: typeof import('./src/components/playListDetail/playListDetail.vue')['default']
    Rank: typeof import('./src/components/rank/rank.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/header/Search.vue')['default']
    SingerList: typeof import('./src/components/singerList/singerList.vue')['default']
    SongList: typeof import('./src/components/songList/songList.vue')['default']
    SongListDetail: typeof import('./src/components/songListDetail/songListDetail.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
